In [1]:
import pandas as pd
import numpy as np

In [2]:
df_fraud = pd.read_json('data.json')

In [3]:
df_fraud.head()

,acct_type,approx_payout_date,body_length,channels,country,currency,delivery_method,description,email_domain,event_created,...,ticket_types,user_age,user_created,user_type,venue_address,venue_country,venue_latitude,venue_longitude,venue_name,venue_state
0,fraudster_event,1266062400,3852,5,US,USD,0.0,"<p><a href=""http://s432.photobucket.com/albums...",gmail.com,1262739706,...,"[{u'event_id': 527017, u'cost': 25.0, u'availa...",36,1259613950,1,717 Washington Avenue,US,25.777471,-80.133433,INK Nightclub - South Beach,FL
1,premium,1296720000,3499,0,US,USD,1.0,"<p>Join us for a quick, one-night, community-b...",ruf.org,1293832670,...,"[{u'event_id': 786878, u'cost': 35.0, u'availa...",149,1280942776,3,,US,32.776566,-79.930922,"The Charleston, SC area",SC
2,premium,1296172800,2601,8,US,USD,1.0,"<h3><span class=""subcategory""><strong>Teacher ...",pvsd.k12.ca.us,1291090956,...,"[{u'event_id': 787337, u'cost': 93.51, u'avail...",214,1272559388,3,10100 Pioneer Blvd Suite 100,US,33.944201,-118.080419,Los Angeles County Office of Education,CA
3,premium,1388966400,12347,6,IE,EUR,1.0,"<p style=""margin-bottom: 1.3em; padding-bottom...",irishtabletennis.com,1360681570,...,"[{u'event_id': 885645, u'cost': 25.0, u'availa...",889,1283870102,3,,None,NaN,NaN,None,None
4,premium,1297900800,2417,11,US,USD,0.0,<p>Writers and filmmakers need to understand t...,artsandbusinesscouncil.org,1291994666,...,"[{u'event_id': 1114349, u'cost': 150.0, u'avai...",35,1288984065,3,One Marina Park Drive,US,42.353848,-71.044276,Fish & Richardson,MA

In [6]:
df_fraud.columns

Index([u'acct_type', u'approx_payout_date', u'body_length', u'channels',
       u'country', u'currency', u'delivery_method', u'description',
       u'email_domain', u'event_created', u'event_end', u'event_published',
       u'event_start', u'fb_published', u'gts', u'has_analytics',
       u'has_header', u'has_logo', u'listed', u'name', u'name_length',
       u'num_order', u'num_payouts', u'object_id', u'org_desc',
       u'org_facebook', u'org_name', u'org_twitter', u'payee_name',
       u'payout_type', u'previous_payouts', u'sale_duration',
       u'sale_duration2', u'show_map', u'ticket_types', u'user_age',
       u'user_created', u'user_type', u'venue_address', u'venue_country',
       u'venue_latitude', u'venue_longitude', u'venue_name', u'venue_state'],
      dtype='object')

In [8]:
df_fraud.shape

(14337, 44)

In [9]:
df_fraud.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14337 entries, 0 to 14336
Data columns (total 44 columns):
acct_type             14337 non-null object
approx_payout_date    14337 non-null int64
body_length           14337 non-null int64
channels              14337 non-null int64
country               14256 non-null object
currency              14337 non-null object
delivery_method       14321 non-null float64
description           14337 non-null object
email_domain          14337 non-null object
event_created         14337 non-null int64
event_end             14337 non-null int64
event_published       14238 non-null float64
event_start           14337 non-null int64
fb_published          14337 non-null int64
gts                   14337 non-null float64
has_analytics         14337 non-null int64
has_header            8928 non-null float64
has_logo              14337 non-null int64
listed                14337 non-null object
name                  14337 non-null object
name_length           14337 non-null int64
num_order             14337 non-null int64
num_payouts           14337 non-null int64
object_id             14337 non-null int64
org_desc              14337 non-null object
org_facebook          14278 non-null float64
org_name              14337 non-null object
org_twitter           14278 non-null float64
payee_name            14337 non-null object
payout_type           14337 non-null object
previous_payouts      14337 non-null object
sale_duration         14182 non-null float64
sale_duration2        14337 non-null int64
show_map              14337 non-null int64
ticket_types          14337 non-null object
user_age              14337 non-null int64
user_created          14337 non-null int64
user_type             14337 non-null int64
venue_address         14337 non-null object
venue_country         13261 non-null object
venue_latitude        13261 non-null float64
venue_longitude       13261 non-null float64
venue_name            13261 non-null object
venue_state           13261 non-null object
dtypes: float64(9), int64(18), object(17)
memory usage: 4.9+ MB

In [10]:
for column in df_fraud.columns:
    print column,": ", df_fraud[column][0:10]

acct_type :  0    fraudster_event
1            premium
2            premium
3            premium
4            premium
5            premium
6            premium
7            premium
8            premium
9            premium
Name: acct_type, dtype: object
approx_payout_date :  0    1266062400
1    1296720000
2    1296172800
3    1388966400
4    1297900800
5    1300496400
6    1297909800
7    1296709200
8    1298185200
9    1297314000
Name: approx_payout_date, dtype: int64
body_length :  0     3852
1     3499
2     2601
3    12347
4     2417
5      117
6       28
7      974
8     4388
9      974
Name: body_length, dtype: int64
channels :  0     5
1     0
2     8
3     6
4    11
5     6
6     5
7    12
8     4
9    12
Name: channels, dtype: int64
country :  0    US
1    US
2    US
3    IE
4    US
5    US
6    US
7    US
8    US
9    US
Name: country, dtype: object
currency :  0    USD
1    USD
2    USD
3    EUR
4    USD
5    USD
6    USD
7    USD
8    USD
9    USD
Name: currency, dtype: object
delivery_method :  0    0.0
1    1.0
2    1.0
3    1.0
4    0.0
5    0.0
6    1.0
7    0.0
8    0.0
9    0.0
Name: delivery_method, dtype: float64
description :  0    <p><a href="http://s432.photobucket.com/albums...
1    <p>Join us for a quick, one-night, community-b...
2    <h3><span class="subcategory"><strong>Teacher ...
3    <p style="margin-bottom: 1.3em; padding-bottom...
4    <p>Writers and filmmakers need to understand t...
5    <p>Come join the Bluegrass Stallions as they t...
6                     <p>Â </p>\r\n<p>Â </p>\r\n<p>Â </p>
7    <p><em>WHEN JEKYLL MET HYDE</em></p>\r\n<p>The...
8    <p style="text-align: center;"><font face="boo...
9    <p><em>WHEN JEKYLL MET HYDE</em></p>\r\n<p>The...
Name: description, dtype: object
email_domain :  0                     gmail.com
1                       ruf.org
2                pvsd.k12.ca.us
3          irishtabletennis.com
4    artsandbusinesscouncil.org
5        bluegrassstallions.com
6                     naboe.org
7        themagnetictheatre.org
8                   credosf.com
9        themagnetictheatre.org
Name: email_domain, dtype: object
event_created :  0    1262739706
1    1293832670
2    1291090956
3    1360681570
4    1291994666
5    1294421810
6    1294425018
7    1294427837
8    1294428122
9    1294428286
Name: event_created, dtype: int64
event_end :  0    1265630400
1    1296288000
2    1295740800
3    1388534400
4    1297468800
5    1300064400
6    1297477800
7    1296277200
8    1297753200
9    1296882000
Name: event_end, dtype: int64
event_published :  0    1.263110e+09
1    1.293833e+09
2    1.291092e+09
3    1.360683e+09
4    1.291995e+09
5    1.294422e+09
6    1.294425e+09
7    1.294428e+09
8    1.294880e+09
9    1.294428e+09
Name: event_published, dtype: float64
event_start :  0    1265594400
1    1296255600
2    1295713800
3    1360702800
4    1297440000
5    1300053600
6    1297468800
7    1296271800
8    1297737000
9    1296876600
Name: event_start, dtype: int64
fb_published :  0    0
1    0
2    0
3    0
4    1
5    0
6    0
7    0
8    1
9    0
Name: fb_published, dtype: int64
gts :  0       0.00
1     868.02
2    3500.00
3    1167.35
4    2313.15
5     302.57
6     832.64
7     220.64
8    3706.36
9     535.84
Name: gts, dtype: float64
has_analytics :  0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: has_analytics, dtype: int64
has_header :  0    1.0
1    0.0
2    NaN
3    0.0
4    0.0
5    0.0
6    1.0
7    0.0
8    0.0
9    0.0
Name: has_header, dtype: float64
has_logo :  0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    1
8    1
9    1
Name: has_logo, dtype: int64
listed :  0    y
1    n
2    y
3    y
4    y
5    y
6    y
7    y
8    y
9    y
Name: listed, dtype: object
name :  0    99 HOUR "NO SLEEP" SUPER BOWL CELEBRITY WEEKEN...
1                          Winthrop RUF Winter Getaway
2                         DRDP (2010) Teacher Training
3                                ITTA Affiliation 2013
4    Self Defense for Writers and Filmmakers: For A...
5         Bluegrass Stallions vs Rochester Razorsharks
6                 Fridays at Four Frederick 2011-02-11
7                         When Jekyll Met Hyde (1960s)
8                                  A Sweetheart Affair
9                         When Jekyll Met Hyde (1950s)
Name: name, dtype: object
name_length :  0    60
1    27
2    28
3    21
4    66
5    44
6    36
7    28
8    19
9    28
Name: name_length, dtype: int64
num_order :  0     0
1    23
2    19
3    39
4    30
5    14
6    12
7     6
8    12
9    14
Name: num_order, dtype: int64
num_payouts :  0     0
1     1
2     4
3    16
4     0
5     3
6     3
7     5
8     0
9     9
Name: num_payouts, dtype: int64
object_id :  0     527017
1     786878
2     787337
3     885645
4    1114349
5    1179983
6    1180179
7    1180391
8    1180423
9    1180435
Name: object_id, dtype: int64
org_desc :  0
1    <p>Since 1987, RUF has ministered to students ...
2    <p><a href="http://www.desiredresults.com">www...
3
4    <p><font face="Arial"><font size="2"><strong>T...
5    <p>The Bluegrass Stallions is Central Kentucky...
6    <div id="organizer_display">\r\n<p>Fridays at ...
7    <p>The only performing arts venue in the south...
8
9    <p>The only performing arts venue in the south...
Name: org_desc, dtype: object
org_facebook :  0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7    18.0
8     0.0
9    18.0
Name: org_facebook, dtype: float64
org_name :  0                Party Starz Ent & Diverse Int'l Group
1                           RUF at Winthrop University
2    University Preparation School in collaboration...
3
4           Arts & Business Council of Greater Boston
5                       Bluegrass Stallions Basketball
6                      NABOE Business Owner Networking
7                                 The Magnetic Theatre
8
9                                 The Magnetic Theatre
Name: org_name, dtype: object
org_twitter :  0     0.0
1    12.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
Name: org_twitter, dtype: float64
payee_name :  0
1                                            RUF
2                  University Preparation School
3
4    Arts and Business Council or Greater Boston
5                            Bluegrass Stallions
6
7
8
9
Name: payee_name, dtype: object
payout_type :  0
1    CHECK
2    CHECK
3      ACH
4    CHECK
5    CHECK
6      ACH
7      ACH
8      ACH
9      ACH
Name: payout_type, dtype: object
previous_payouts :  0                                                   []
1    [{u'name': u'RUF', u'created': u'2010-10-01 01...
2    [{u'name': u'Danielle Severn', u'created': u'2...
3    [{u'name': u'', u'created': u'2010-11-09 01:10...
4    [{u'name': u'Arts and Business Council or Grea...
5    [{u'name': u'Bluegrass Stallions', u'created':...
6    [{u'name': u'', u'created': u'2011-01-12 01:12...
7    [{u'name': u'', u'created': u'2011-01-25 01:12...
8    [{u'name': u'', u'created': u'2011-02-19 01:12...
9    [{u'name': u'', u'created': u'2011-01-25 01:12...
Name: previous_payouts, dtype: object
sale_duration :  0    29.0
1    28.0
2    54.0
3     0.0
4    63.0
5    65.0
6    35.0
7    21.0
8    33.0
9    28.0
Name: sale_duration, dtype: float64
sale_duration2 :  0    33
1    28
2    54
3     0
4    63
5    65
6    35
7    21
8    38
9    28
Name: sale_duration2, dtype: int64
show_map :  0    1
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    0
9    1
Name: show_map, dtype: int64
ticket_types :  0    [{u'event_id': 527017, u'cost': 25.0, u'availa...
1    [{u'event_id': 786878, u'cost': 35.0, u'availa...
2    [{u'event_id': 787337, u'cost': 93.51, u'avail...
3    [{u'event_id': 885645, u'cost': 25.0, u'availa...
4    [{u'event_id': 1114349, u'cost': 150.0, u'avai...
5    [{u'event_id': 1179983, u'cost': 8.0, u'availa...
6    [{u'event_id': 1180179, u'cost': 22.63, u'avai...
7    [{u'event_id': 1180391, u'cost': 14.0, u'avail...
8    [{u'event_id': 1180423, u'cost': 250.0, u'avai...
9    [{u'event_id': 1180435, u'cost': 14.0, u'avail...
Name: ticket_types, dtype: object
user_age :  0     36
1    149
2    214
3    889
4     35
5    299
6    706
7     71
8      0
9     71
Name: user_age, dtype: int64
user_created :  0    1259613950
1    1280942776
2    1272559388
3    1283870102
4    1288984065
5    1268579110
6    1233437951
7    1288276103
8    1294428121
9    1288276103
Name: user_created, dtype: int64
user_type :  0    1
1    3
2    3
3    3
4    3
5    1
6    3
7    3
8    3
9    3
Name: user_type, dtype: int64
venue_address :  0           717 Washington Avenue
1
2    10100 Pioneer Blvd Suite 100
3
4          One Marina Park Drive
5
6                      6N East St
7                372 Depot Street
8           465 California Street
9                372 Depot Street
Name: venue_address, dtype: object
venue_country :  0      US
1      US
2      US
3    None
4      US
5      US
6      US
7      US
8      US
9      US
Name: venue_country, dtype: object
venue_latitude :  0    25.777471
1    32.776566
2    33.944201
3          NaN
4    42.353848
5    38.209797
6    39.414270
7    35.580468
8    37.792847
9    35.580468
Name: venue_latitude, dtype: float64
venue_longitude :  0    -80.133433
1    -79.930922
2   -118.080419
3           NaN
4    -71.044276
5    -84.558831
6    -77.405089
7    -82.563855
8   -122.402082
9    -82.563855
Name: venue_longitude, dtype: float64
venue_name :  0               INK Nightclub - South Beach
1                   The Charleston, SC area
2    Los Angeles County Office of Education
3                                      None
4                         Fish & Richardson
5       Georgetown College Alumni Gymnasium
6                     Danielle's Restaurant
7                        The Magnetic Field
8
9                        The Magnetic Field
Name: venue_name, dtype: object
venue_state :  0      FL
1      SC
2      CA
3    None
4      MA
5      KY
6      MD
7      NC
8
9      NC
Name: venue_state, dtype: object

In [28]:
df_fraud.ticket_types[0]

[{u'availability': 1,
  u'cost': 25.0,
  u'event_id': 527017,
  u'quantity_sold': 0,
  u'quantity_total': 800},
 {u'availability': 1,
  u'cost': 50.0,
  u'event_id': 527017,
  u'quantity_sold': 0,
  u'quantity_total': 100},
 {u'availability': 1,
  u'cost': 550.0,
  u'event_id': 527017,
  u'quantity_sold': 0,
  u'quantity_total': 20}]

In [19]:
df_fraud.acct_type.unique()

array([u'fraudster_event', u'premium', u'spammer_warn', u'fraudster',
       u'spammer_limited', u'spammer_noinvite', u'locked', u'tos_lock',
       u'tos_warn', u'fraudster_att', u'spammer_web', u'spammer'], dtype=object)

In [21]:
df_fraud.acct_type.value_counts()

premium             12373
fraudster_event       851
fraudster             437
spammer_limited       218
spammer_warn          144
tos_warn               91
spammer_noinvite       84
tos_lock               77
locked                 54
fraudster_att           5
spammer_web             2
spammer                 1
Name: acct_type, dtype: int64

In [22]:
df_fraud.delivery_method.value_counts()

0.0    8520
1.0    5554
3.0     247
Name: delivery_method, dtype: int64

In [23]:
df_fraud.email_domain.value_counts()

gmail.com                       3097
yahoo.com                        792
hotmail.com                      399
aol.com                          198
live.com                          80
me.com                            75
ymail.com                         68
comcast.net                       60
generalassemb.ly                  58
kineticevents.com                 52
yahoo.co.uk                       52
hotmail.co.uk                     48
improvboston.com                  46
sippingnpainting.com              39
claytonislandtours.com            37
lidf.co.uk                        35
racetonowhere.com                 35
live.fr                           33
greatworldadventures.com          31
yahoo.ca                          31
shaw.ca                           28
sbcglobal.net                     26
msn.com                           25
mac.com                           25
guardian.co.uk                    24
live.co.uk                        24
rocketmail.com                    23
joonbug.com                       23
busboysandpoets.com               21
jhilburn.com                      21
                                ...
gccnh.com                          1
connecteduk.org                    1
leadershipmemphis.org              1
christmascrawl.com                 1
lesfilmfestival.com                1
livingwellcounselling.ca           1
gregorywhitepr.com                 1
live-life-smiling.com              1
bruisedfruitpromotions.com         1
jimstrickland2012.com              1
sycamoreschools.org                1
harcvs.org.uk                      1
kailocs.com                        1
indiabestplace.com                 1
417mag.com                         1
Calvaryphx.com                     1
stjohnvianney.net                  1
idealpublicity.com                 1
marketeeringgroup.com              1
milanimedia.com                    1
uplandbeer.com                     1
ltefnj.org                         1
alicestapleton.com                 1
thelotinitiative.org               1
stantec.com                        1
hopecorby.org                      1
calvaryconnect.com                 1
eiffelsociety.com                  1
businessgolfconnection.com         1
meet-the-artist-concerts.com       1
Name: email_domain, dtype: int64

In [24]:
df_fraud.org_facebook.value_counts()

0.0     8097
12.0     509
16.0     423
14.0     413
15.0     391
13.0     389
11.0     345
10.0     343
18.0     277
9.0      276
17.0     257
8.0      216
19.0     211
20.0     190
23.0     181
21.0     165
7.0      159
22.0     135
6.0       96
39.0      86
24.0      84
29.0      60
28.0      59
5.0       58
25.0      56
27.0      51
32.0      51
26.0      50
30.0      40
33.0      39
        ...
61.0       9
62.0       8
54.0       7
50.0       5
81.0       5
76.0       5
59.0       4
58.0       4
67.0       4
64.0       3
71.0       3
57.0       3
65.0       3
66.0       3
4.0        3
91.0       3
3.0        2
70.0       2
73.0       2
83.0       2
63.0       2
72.0       2
78.0       2
69.0       1
88.0       1
60.0       1
75.0       1
85.0       1
80.0       1
79.0       1
Name: org_facebook, dtype: int64